[[plugin.deps]]
use = "yazi-rs/plugins:smart-enter"
rev = "2730199"
hash = "7918aab6a71caf31b58411f789195677"

[[plugin.deps]]
use = "yazi-rs/plugins:smart-filter"
rev = "2730199"
hash = "f0c4b41b5d19a3144958383333eff6e7"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "2730199"
hash = "2f1053f89d1a301a648ab181d0948e38"

[[plugin.deps]]
use = "stelcodes/bunny"
rev = "7137a44"
hash = "58bfa473bcac8574400e573787954512"

[[plugin.deps]]
use = "orhnk/system-clipboard"
rev = "888026c"
hash = "9f82a544335a53d79e87ea315746caaa"

[flavor]
deps = []
