[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/dotfiles"
desc = "cd to ~/dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd /mnt/Synology/"
desc = "cd to /mnt/Synology/"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/projects/"
desc = "cd to ~/projects/"

## plugins

# [[manager.prepend_keymap]]
# on   = "l"
# run  = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "b"
run = "plugin bunny"
desc = "Start bunny.yazi"

# Optionally, add another keymap to immediately fuzzy search bookmarks
[[mgr.prepend_keymap]]
on = "'"
run = "plugin bunny fuzzy"
desc = "Start bunny.yazi fuzzy search"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on = ["R","b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"
