shell = "zsh"

[plugins]

[plugins.init]
inline = "autoload -Uz compinit && compinit -i"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]

[plugins.zoxide]
github = "ajeetdsouza/zoxide"

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"

[plugins.history-search-multi-word]
github = "zdharma/history-search-multi-word"

[plugins.zoxide-init]
inline = 'eval "$(zoxide init zsh)"'
